[[t8code]]
arch = "aarch64"
git-tree-sha1 = "c79a1619bb8af0dc87f51226fcd352ce5c5f248c"
lazy = true
mpi = "mpich"
os = "macos"

    [[t8code.download]]
    sha256 = "59b246a1c41d5b6811eb487a83604c3acf1ffc6f561294b5282f7b612290c394"
    url = "https://github.com/jmark/t8code_jll.jl/releases/download/t8code-v3.0.0+0/t8code.v3.0.0.aarch64-apple-darwin-mpi+mpich.tar.gz"
[[t8code]]
arch = "aarch64"
git-tree-sha1 = "2a7ecf1095c38b266e2493d66ab914fd8fbb3ebe"
lazy = true
mpi = "mpitrampoline"
os = "macos"

    [[t8code.download]]
    sha256 = "11183266ba4a0619127e257ce9c731c70678c35370586e8c3b6c5eaf4cc3ed4c"
    url = "https://github.com/jmark/t8code_jll.jl/releases/download/t8code-v3.0.0+0/t8code.v3.0.0.aarch64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[t8code]]
arch = "aarch64"
git-tree-sha1 = "cc1cdcb60b5bc9d48ad367ab4fd6bf05cd810124"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[t8code.download]]
    sha256 = "98a733254ec1a5f698dfde9cd2dfe500886e1ed1c08876aa20ad545356f604b9"
    url = "https://github.com/jmark/t8code_jll.jl/releases/download/t8code-v3.0.0+0/t8code.v3.0.0.aarch64-linux-gnu-mpi+mpich.tar.gz"
[[t8code]]
arch = "aarch64"
git-tree-sha1 = "856c7e7ac01bf7e2cdbfaabcce8bb5ea3a6de36e"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[t8code.download]]
    sha256 = "4f12f832addd43d8b27b1904c03477dbfc24698ca6ab422a19b756871f83746b"
    url = "https://github.com/jmark/t8code_jll.jl/releases/download/t8code-v3.0.0+0/t8code.v3.0.0.aarch64-linux-gnu-mpi+mpitrampoline.tar.gz"
[[t8code]]
arch = "aarch64"
git-tree-sha1 = "475c55906afc8512c83779b3e886c6aba49a9b46"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[t8code.download]]
    sha256 = "01d9d5f1d4d3d4c0b60ec3cb2b486c54e2f780fbe3eab288eec3a1f48e5367cd"
    url = "https://github.com/jmark/t8code_jll.jl/releases/download/t8code-v3.0.0+0/t8code.v3.0.0.aarch64-linux-musl-mpi+mpich.tar.gz"
[[t8code]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b9d455a319bb9735aa9921ec911a46e3ac4c460a"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[t8code.download]]
    sha256 = "80f9b85bd2c656b32a47fdc767c0fe8957af0c6db7077cc2b7cad925dad209d6"
    url = "https://github.com/jmark/t8code_jll.jl/releases/download/t8code-v3.0.0+0/t8code.v3.0.0.armv6l-linux-gnueabihf-mpi+mpich.tar.gz"
[[t8code]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d747f22619be6900008ed5a536c29cdebfbc86e6"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[t8code.download]]
    sha256 = "8c60f8a89047807288320d5b8800bf67dda0d0091bfa3dc3c575c1bd439d3a83"
    url = "https://github.com/jmark/t8code_jll.jl/releases/download/t8code-v3.0.0+0/t8code.v3.0.0.armv6l-linux-gnueabihf-mpi+mpitrampoline.tar.gz"
[[t8code]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d564ab59d791e6e2763a54bd51e858e83df9c698"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[t8code.download]]
    sha256 = "a4ff6447bbeb0c0a4c5acd3c1099161549cdd3cd17141d1e67135f92ea7fc7a1"
    url = "https://github.com/jmark/t8code_jll.jl/releases/download/t8code-v3.0.0+0/t8code.v3.0.0.armv6l-linux-musleabihf-mpi+mpich.tar.gz"
[[t8code]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bfc3ffc066ef977a01d805a97a239bdc590e9fc7"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[t8code.download]]
    sha256 = "aaa12f6c618b44d2a2688237955d6462a9085972428065b4d3e02ba486c68a47"
    url = "https://github.com/jmark/t8code_jll.jl/releases/download/t8code-v3.0.0+0/t8code.v3.0.0.armv7l-linux-gnueabihf-mpi+mpich.tar.gz"
[[t8code]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "191846c5ade44a91db6d518ba878b19558ebb631"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[t8code.download]]
    sha256 = "f8522114efaec5cb1ad35ac7176541f1980a3c5b9f14add585a55573acba61a6"
    url = "https://github.com/jmark/t8code_jll.jl/releases/download/t8code-v3.0.0+0/t8code.v3.0.0.armv7l-linux-gnueabihf-mpi+mpitrampoline.tar.gz"
[[t8code]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "86b157b27586f7a8ebd96e8f621d7622fca82aff"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[t8code.download]]
    sha256 = "df9d91ad66974994f54d7967a95cde98669fb7d5b8c13b8215f3adf15d1072b8"
    url = "https://github.com/jmark/t8code_jll.jl/releases/download/t8code-v3.0.0+0/t8code.v3.0.0.armv7l-linux-musleabihf-mpi+mpich.tar.gz"
[[t8code]]
arch = "i686"
git-tree-sha1 = "1e15b48157703e562627ee79d1cdc1b7ee66dbb0"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[t8code.download]]
    sha256 = "337d63924bbdc1a7254f5ac6b28ea4f2658ab8b1db08841fc6a5af9b4f267a47"
    url = "https://github.com/jmark/t8code_jll.jl/releases/download/t8code-v3.0.0+0/t8code.v3.0.0.i686-linux-gnu-mpi+mpich.tar.gz"
[[t8code]]
arch = "i686"
git-tree-sha1 = "268a46d9a58dae3f0c5d2d7518de5baf641fd5e6"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[t8code.download]]
    sha256 = "f22ac4068402550d12887268507c350a04d3a6a1c3fd1d2f1a79c41efd5f578d"
    url = "https://github.com/jmark/t8code_jll.jl/releases/download/t8code-v3.0.0+0/t8code.v3.0.0.i686-linux-gnu-mpi+mpitrampoline.tar.gz"
[[t8code]]
arch = "i686"
git-tree-sha1 = "55fb4a80b2dd902a150eae8c798cf020ac91dbd6"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[t8code.download]]
    sha256 = "645af0608328c8b003c6b885447054abb76813ae58024241c52214deb3e991d7"
    url = "https://github.com/jmark/t8code_jll.jl/releases/download/t8code-v3.0.0+0/t8code.v3.0.0.i686-linux-musl-mpi+mpich.tar.gz"
[[t8code]]
arch = "powerpc64le"
git-tree-sha1 = "daa82bce5a89bf25e7d10fc471fd5e52ae50984d"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[t8code.download]]
    sha256 = "69bd2eab7b90d788ddac06cf2f4df06c0291be445a01796f457c415d4643bd0b"
    url = "https://github.com/jmark/t8code_jll.jl/releases/download/t8code-v3.0.0+0/t8code.v3.0.0.powerpc64le-linux-gnu-mpi+mpich.tar.gz"
[[t8code]]
arch = "powerpc64le"
git-tree-sha1 = "fac3bc227ee9f0fcbf4a5095bc2f0520ffadb262"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[t8code.download]]
    sha256 = "1cc06358e0be73856e0fadd8ed27caa7a03b591390b953be8807effc87e59406"
    url = "https://github.com/jmark/t8code_jll.jl/releases/download/t8code-v3.0.0+0/t8code.v3.0.0.powerpc64le-linux-gnu-mpi+mpitrampoline.tar.gz"
[[t8code]]
arch = "x86_64"
git-tree-sha1 = "e1851eb7874383ec54bef759fcbf47d1c6b9bd03"
lazy = true
mpi = "mpich"
os = "macos"

    [[t8code.download]]
    sha256 = "275354a0c8871b63938f186ec5227513da37bacf68bb8172202bff5877950db4"
    url = "https://github.com/jmark/t8code_jll.jl/releases/download/t8code-v3.0.0+0/t8code.v3.0.0.x86_64-apple-darwin-mpi+mpich.tar.gz"
[[t8code]]
arch = "x86_64"
git-tree-sha1 = "6ca4f2b8cdb5b82cd1603e72c492425cc5570c02"
lazy = true
mpi = "mpitrampoline"
os = "macos"

    [[t8code.download]]
    sha256 = "f0447b8ba85fefe7f4839c94316669d0031cc54b227579536be67bbe7b6aa3d9"
    url = "https://github.com/jmark/t8code_jll.jl/releases/download/t8code-v3.0.0+0/t8code.v3.0.0.x86_64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[t8code]]
arch = "x86_64"
git-tree-sha1 = "83d2166d8054106e69cbb8122fc6336a3d7829fd"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[t8code.download]]
    sha256 = "b9e762427be1d8801a12ccb70afcfb20a672e6402b878143b738520d4aafc843"
    url = "https://github.com/jmark/t8code_jll.jl/releases/download/t8code-v3.0.0+0/t8code.v3.0.0.x86_64-linux-gnu-mpi+mpich.tar.gz"
[[t8code]]
arch = "x86_64"
git-tree-sha1 = "920658660245847866722f9dd36dd12870fd2ab2"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[t8code.download]]
    sha256 = "94ae022309002207a7aeb202217abdfd3cd682cade24dde502fee6d741fc45ad"
    url = "https://github.com/jmark/t8code_jll.jl/releases/download/t8code-v3.0.0+0/t8code.v3.0.0.x86_64-linux-gnu-mpi+mpitrampoline.tar.gz"
[[t8code]]
arch = "x86_64"
git-tree-sha1 = "28d361b37c3def150d4d6d2059cd4e035f2639ea"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[t8code.download]]
    sha256 = "43b23e1a46ed874ab14597f4f29e25354479bc250202da9f83d9e8e4cb8ad7b6"
    url = "https://github.com/jmark/t8code_jll.jl/releases/download/t8code-v3.0.0+0/t8code.v3.0.0.x86_64-linux-musl-mpi+mpich.tar.gz"
[[t8code]]
arch = "x86_64"
git-tree-sha1 = "04707fc9373ca710a5d533ec8fc75313d4020052"
lazy = true
mpi = "mpich"
os = "freebsd"

    [[t8code.download]]
    sha256 = "c30e31d355d600662a11d6c1e533488568e67dfd8fe98265656916f9f9b99679"
    url = "https://github.com/jmark/t8code_jll.jl/releases/download/t8code-v3.0.0+0/t8code.v3.0.0.x86_64-unknown-freebsd-mpi+mpich.tar.gz"
[[t8code]]
arch = "x86_64"
git-tree-sha1 = "750d1b66d8f224f21872342e3ea16a0a30f9d1cc"
lazy = true
mpi = "microsoftmpi"
os = "windows"

    [[t8code.download]]
    sha256 = "95710e17697c6c71868b678b948e6a4d4039e1b35b00ffd1ad82650efe4dc567"
    url = "https://github.com/jmark/t8code_jll.jl/releases/download/t8code-v3.0.0+0/t8code.v3.0.0.x86_64-w64-mingw32-mpi+microsoftmpi.tar.gz"
