[[t8code]]
arch = "aarch64"
git-tree-sha1 = "53e66d3993138abbc4ca95568dbfdc8f344b03dd"
lazy = true
mpi = "mpich"
os = "macos"

    [[t8code.download]]
    sha256 = "f5a8b156bbb5847b90531fb8ef3f8dede369a04c645ffba5ff5580b800db535c"
    url = "https://github.com/jmark/t8code_jll.jl/releases/download/t8code-v3.0.1+0/t8code.v3.0.1.aarch64-apple-darwin-mpi+mpich.tar.gz"
[[t8code]]
arch = "aarch64"
git-tree-sha1 = "c96d18aaa78ac5dc9c7131188400d99a557d4c46"
lazy = true
mpi = "mpitrampoline"
os = "macos"

    [[t8code.download]]
    sha256 = "6db726babc6b86dfbfc031cb88891dd1da97d10b82015714875262bd3614aa56"
    url = "https://github.com/jmark/t8code_jll.jl/releases/download/t8code-v3.0.1+0/t8code.v3.0.1.aarch64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[t8code]]
arch = "aarch64"
git-tree-sha1 = "40f01e7c8b491ba30b6400477502ad9b9332d19a"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[t8code.download]]
    sha256 = "58e9d349146c75199090a2ead50917edc4ce1e4ed9596810d495a7273e2283bc"
    url = "https://github.com/jmark/t8code_jll.jl/releases/download/t8code-v3.0.1+0/t8code.v3.0.1.aarch64-linux-gnu-mpi+mpich.tar.gz"
[[t8code]]
arch = "aarch64"
git-tree-sha1 = "0a5bcee0452a294e8a0b85585f2511aaa1e1dcc7"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[t8code.download]]
    sha256 = "9b73d3ebd9e18af0f342fa4f19289542a89db41dafa6f62ec54f26cb9442c98a"
    url = "https://github.com/jmark/t8code_jll.jl/releases/download/t8code-v3.0.1+0/t8code.v3.0.1.aarch64-linux-gnu-mpi+mpitrampoline.tar.gz"
[[t8code]]
arch = "aarch64"
git-tree-sha1 = "0999fc1b23acf5a6b5ff017d8edd756decb28716"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[t8code.download]]
    sha256 = "bdaecae2bc34a6ebe74644e6c167c2669882888d5041ec3a41de2efb0eae7a8a"
    url = "https://github.com/jmark/t8code_jll.jl/releases/download/t8code-v3.0.1+0/t8code.v3.0.1.aarch64-linux-musl-mpi+mpich.tar.gz"
[[t8code]]
arch = "aarch64"
git-tree-sha1 = "0626c7812b54d0c2dbb09b93798a3233e14588af"
lazy = true
mpi = "mpich"
os = "freebsd"

    [[t8code.download]]
    sha256 = "c86ed13db9e29efeed7c43a7c046dfbb2582e6a536bb0a209bc3349b0fe8f95e"
    url = "https://github.com/jmark/t8code_jll.jl/releases/download/t8code-v3.0.1+0/t8code.v3.0.1.aarch64-unknown-freebsd-mpi+mpich.tar.gz"
[[t8code]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ac13d7dcad2246c5839608947692a72104c73e49"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[t8code.download]]
    sha256 = "4fef8631cc7bc571be68359b5e3f3450cb0221b5a83dcf39bbb48027a9859c3f"
    url = "https://github.com/jmark/t8code_jll.jl/releases/download/t8code-v3.0.1+0/t8code.v3.0.1.armv6l-linux-gnueabihf-mpi+mpich.tar.gz"
[[t8code]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "82b4a3c709834d61cb990ae7d4b20a26dd1bd257"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[t8code.download]]
    sha256 = "c61d9d6f4dfecea3169b9a8245f75603d059e40b22ba914a338248d6850b4b53"
    url = "https://github.com/jmark/t8code_jll.jl/releases/download/t8code-v3.0.1+0/t8code.v3.0.1.armv6l-linux-gnueabihf-mpi+mpitrampoline.tar.gz"
[[t8code]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ee55973ccd9259a32a8736bc2f4b1cb561ec46b5"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[t8code.download]]
    sha256 = "45d4de72b0b60553f7c610bf50a1aedc2d8e7f533caf52f05e2860244eb757a0"
    url = "https://github.com/jmark/t8code_jll.jl/releases/download/t8code-v3.0.1+0/t8code.v3.0.1.armv6l-linux-musleabihf-mpi+mpich.tar.gz"
[[t8code]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0c1afba07775f4812b50637f881311a490e8160d"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[t8code.download]]
    sha256 = "b694a66fca1882e8e69e00e33b032b292e498a61a3ccd429898061e95d3dd47c"
    url = "https://github.com/jmark/t8code_jll.jl/releases/download/t8code-v3.0.1+0/t8code.v3.0.1.armv7l-linux-gnueabihf-mpi+mpich.tar.gz"
[[t8code]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b1b0a3932a6070fcf2db4db9358dc0bb58a40a2d"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[t8code.download]]
    sha256 = "b570f621741dd3393e2132e409dc603fc8d497560b59395b3074367459ed5f94"
    url = "https://github.com/jmark/t8code_jll.jl/releases/download/t8code-v3.0.1+0/t8code.v3.0.1.armv7l-linux-gnueabihf-mpi+mpitrampoline.tar.gz"
[[t8code]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7b61d50ba5c8952f7b3c876a0e0bd8fedec5bba1"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[t8code.download]]
    sha256 = "119462ddb5377e8c505ad83d5610a4cf6ac348cbe6523069899cfdad604e19dc"
    url = "https://github.com/jmark/t8code_jll.jl/releases/download/t8code-v3.0.1+0/t8code.v3.0.1.armv7l-linux-musleabihf-mpi+mpich.tar.gz"
[[t8code]]
arch = "i686"
git-tree-sha1 = "7dc4238cfe400c391d5781c0b6aefcb64c71dbbf"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[t8code.download]]
    sha256 = "74b48d891120151331fa026202e25615f782f9acbbb8e016ee820e7af6a7886a"
    url = "https://github.com/jmark/t8code_jll.jl/releases/download/t8code-v3.0.1+0/t8code.v3.0.1.i686-linux-gnu-mpi+mpich.tar.gz"
[[t8code]]
arch = "i686"
git-tree-sha1 = "169c11e1004e01ad08797c54830266bb23b8f8a4"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[t8code.download]]
    sha256 = "6ba37b809659e7eb83b7f5d2338a9de2de7c1efb5543639e5323b9a005410959"
    url = "https://github.com/jmark/t8code_jll.jl/releases/download/t8code-v3.0.1+0/t8code.v3.0.1.i686-linux-gnu-mpi+mpitrampoline.tar.gz"
[[t8code]]
arch = "i686"
git-tree-sha1 = "fc26aba5d35c09775ff91b9463033d0e4559d073"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[t8code.download]]
    sha256 = "3de0a9c42eb372d7d85fc782c044b59fcc6cdcc210868e812230a5cd780c612f"
    url = "https://github.com/jmark/t8code_jll.jl/releases/download/t8code-v3.0.1+0/t8code.v3.0.1.i686-linux-musl-mpi+mpich.tar.gz"
[[t8code]]
arch = "powerpc64le"
git-tree-sha1 = "123df6ae92537f7673cac84fad2fe067817c85ca"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[t8code.download]]
    sha256 = "809e6ba73528bc4b0b63cb90218c2d090ecf620779897ad1168d963002adbcbf"
    url = "https://github.com/jmark/t8code_jll.jl/releases/download/t8code-v3.0.1+0/t8code.v3.0.1.powerpc64le-linux-gnu-mpi+mpich.tar.gz"
[[t8code]]
arch = "powerpc64le"
git-tree-sha1 = "d66950a7bbc487150aacf78019e9d7f18880b806"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[t8code.download]]
    sha256 = "76abc55ec74d2a051de3fe50717788e6c8e62a6217c5582b4c86f1425f1f0f73"
    url = "https://github.com/jmark/t8code_jll.jl/releases/download/t8code-v3.0.1+0/t8code.v3.0.1.powerpc64le-linux-gnu-mpi+mpitrampoline.tar.gz"
[[t8code]]
arch = "x86_64"
git-tree-sha1 = "9f64b8820f9c6edbbd757b14cccfaf9565441de4"
lazy = true
mpi = "mpich"
os = "macos"

    [[t8code.download]]
    sha256 = "1e7db69218d356e826f4c8dea86428686cca6a5a5115386758076d9cf8499068"
    url = "https://github.com/jmark/t8code_jll.jl/releases/download/t8code-v3.0.1+0/t8code.v3.0.1.x86_64-apple-darwin-mpi+mpich.tar.gz"
[[t8code]]
arch = "x86_64"
git-tree-sha1 = "1562ad95c076a8f8c06ed250ec4a7a489be9c4c5"
lazy = true
mpi = "mpitrampoline"
os = "macos"

    [[t8code.download]]
    sha256 = "2ddec8ccbba750e7878f17fd6b05559f592b64585f10fc572b4efc5ba8b026cc"
    url = "https://github.com/jmark/t8code_jll.jl/releases/download/t8code-v3.0.1+0/t8code.v3.0.1.x86_64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[t8code]]
arch = "x86_64"
git-tree-sha1 = "a78f73b0c479419db15530096f69a20d96f6d833"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[t8code.download]]
    sha256 = "d3b51e58acd048a35ca8040f819928704f24026c303d2c8e093936762503749d"
    url = "https://github.com/jmark/t8code_jll.jl/releases/download/t8code-v3.0.1+0/t8code.v3.0.1.x86_64-linux-gnu-mpi+mpich.tar.gz"
[[t8code]]
arch = "x86_64"
git-tree-sha1 = "8143be0c2b06f8e4fc7eb750241e3e76ac1ed8bd"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[t8code.download]]
    sha256 = "22e020d5285dc33cd494ad51d2c80b92521077349c95a3ddc65cef21efe8aaf5"
    url = "https://github.com/jmark/t8code_jll.jl/releases/download/t8code-v3.0.1+0/t8code.v3.0.1.x86_64-linux-gnu-mpi+mpitrampoline.tar.gz"
[[t8code]]
arch = "x86_64"
git-tree-sha1 = "5a7cb776fd2ff646390626cf5a19840e74a5aca8"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[t8code.download]]
    sha256 = "41dd9901606066d8dcb7c372e5259eb971b99380ee945b8a77da134d7a054599"
    url = "https://github.com/jmark/t8code_jll.jl/releases/download/t8code-v3.0.1+0/t8code.v3.0.1.x86_64-linux-musl-mpi+mpich.tar.gz"
[[t8code]]
arch = "x86_64"
git-tree-sha1 = "28475cf082e7abb135b65285081f182da6ff5a33"
lazy = true
mpi = "mpich"
os = "freebsd"

    [[t8code.download]]
    sha256 = "6843354522b523fad571cda6d591f7a2a6fd29417d41a3be6bb35e88a0195e3a"
    url = "https://github.com/jmark/t8code_jll.jl/releases/download/t8code-v3.0.1+0/t8code.v3.0.1.x86_64-unknown-freebsd-mpi+mpich.tar.gz"
[[t8code]]
arch = "x86_64"
git-tree-sha1 = "ad936ec247baf87043b93b4fde15cc0118131123"
lazy = true
mpi = "microsoftmpi"
os = "windows"

    [[t8code.download]]
    sha256 = "349c2a29766e6a7cdbcfc87db1a075660487505ddf37efd730cffd0024422676"
    url = "https://github.com/jmark/t8code_jll.jl/releases/download/t8code-v3.0.1+0/t8code.v3.0.1.x86_64-w64-mingw32-mpi+microsoftmpi.tar.gz"
